VRAM_X          =       320 ; horizontalni velikost obrazovky
VRAM_Y          =       200 ; pocet vertikalnich paprsku
MAX_X           =       320 ; pocet horizontalnich paprsku
VZD_OBR         =       256 ; vzdalenost od obrazovky
uhel_odklonu    =       115 ; uhel od s. prvniho paprsku od kolmice s. pohledu
koef_uhlu       =       182 ; kolik casti ma jeden stupen
delta_paprsku   =       28  ; uhel, ktery sviraji sousedni horizontalni paprs.
ZAKL_POS	=	2000; umisteni na mape


